### ISSUE TITLE
延时

### ISSUE THREAD

**Issue by 7086cmd** [oier-byh/freeproxy#1]
V2RayNG跑了4451ms的延时？！
家里的WiFi

**Comment by oier-byh** [comment]
请提供您的优选 Cloudflare IP，因地域原因，可能不同的区域速度不同。
[Better Cloudflare IP](https://github.com/badafans/better-cloudflare-ip)，建议使用 Linux 自行编译获取，期望宽带可设成 100Mbps

**Comment by oier-byh** [comment]
请提供您的优选 Cloudflare IP，因地域原因，可能不同的区域速度不同。
[Better Cloudflare IP](https://github.com/badafans/better-cloudflare-ip)，建议使用 Linux 自行编译获取，期望宽带可设成 100Mbps
